### ISSUE TITLE
Лекция 3, опечатка в формуле

### ISSUE THREAD

**Issue by shihova-asya** [esokolov/ml-course-hse#10]
В лекции 3, стр. 5, раздел "Штрафы при малых весах"
в обеих формулах по L2-норму нужно убрать верхний индекс

**Comment by esokolov** [comment]
Вы уверены? Верхний индекс там как раз означает, что мы возводим значение нормы в квадрат — то есть избавляемся от квадратного корня. Значение после знака равенства согласуется с этим.

**Comment by shihova-asya** [comment]
Да, Вы правы, извините за ложную тревогу :(
