### ISSUE TITLE
2019-fall/hw-07

### ISSUE THREAD

**Issue by igor4149** [esokolov/ml-course-hse#103]
Задание 3.

Подберите оптимальные с точки зрения метрики качества параметры алгоритмов, изменяя:

...
* оптимизируемый функционал.

CatBoost по умолчанию поддерживает для классификации только логлосс и кросс-энтропию (которые формулируются эквивалентно для бинарной задачи). Собственные функции потерь сами разработчики рекомендуют писать на С++ [(пруф)](https://github.com/catboost/catboost/issues/521). Как быть?

С LightGBM то же самое, по умолчанию он поддерживает только логлосс, собственные функции потерь требуется писать с гессианами.

**Comment by Kokhtev** [comment]
Действительно, для бинарной классификации не получится подобрать функционал, этот пункт можно игнорировать, а задание будет обновлено
