### ISSUE TITLE
Лекции в исходниках

### ISSUE THREAD

**Issue by luc1ph3r** [esokolov/ml-course-hse#11]
Было бы удобно, если бы лекции были выложены в исходниках (TeX), чтобы вместо создания  issue можно было просто предложить Pull Request.

**Comment by luc1ph3r** [comment]
`ping`
Если ничего изменяться не будет, то закройте хотя бы issue (:

**Comment by esokolov** [comment]
Выложить исходники мы планируем, но это случится, скорее всего, ближе к концу учебного года — до этого есть некоторые трудности. Пока придётся работать в тикетах :)

**Comment by s-mx** [comment]
Конец курса вроде прошел, так что можно выкладывать исходники :)
