### ISSUE TITLE
Домашнее задание по GLM 

### ISSUE THREAD

**Issue by iknunyants** [esokolov/ml-course-hse#124]
Подправьте, пожалуйста, уже написанный вами код, он либо в некоторых местах не работает (train_test_split), либо сигнатура соответствует старым версиям библиотек (OneHotEncoder больше не имеет аргумента categorical_features). Если это конечно не является частью задания.

**Comment by esokolov** [comment]
Вроде поправил, но пишите, если что-то не будет заводиться
