### ISSUE TITLE
Ошибка в Лекции 5, SVM (2020)?

### ISSUE THREAD

**Issue by Crowbar97** [esokolov/ml-course-hse#133]
В [лекции 5](https://github.com/esokolov/ml-course-hse/blob/master/2020-fall/lecture-notes/lecture05-linclass.pdf) в формуле 2.2 указано, что минимизация нормы ||w|| ^ 2 весов производится по двум параметрам: вектору весов w и смещению b. Вопрос: Если смещение b не входит в вектор весов в данном случае, то нужно ли его указывать? Аналогично в формуле 2.3.

**Comment by esokolov** [comment]
Указывать нужно — да, смещение b не входит в сам функционал, но при этом мы вольны выбирать его так, чтобы выполнить ограничения. Поэтому b указывается среди переменных, по которым выполняется минимизация, в знак того, что его мы тоже подбираем, это не константа.

**Comment by Crowbar97** [comment]
Понял, спасибо!
