### ISSUE TITLE
Лекция 9 (бустинг)

### ISSUE THREAD

**Issue by Combo-Breaker** [esokolov/ml-course-hse#15]
1. Кажется, в последней формуле по регрессии (вычисление антиградиента) не должно быть суммы в производной, ведь мы считаем i-тую компоненту.
2. И вопрос: почему в этом же разделе в MSE множитель 1/2, а не 1/L?

**Comment by esokolov** [comment]
1. Спасибо, поправлю.
2. Этот множитель ведь ни на что не влияет, поэтому можно выбирать его любым. Тут 1/2 удобнее с точки зрения арифметики.
