### ISSUE TITLE
Семинар 9, кажется знак потеряли

### ISSUE THREAD

**Issue by IL2-RUS** [esokolov/ml-course-hse#16]
Страница 5, в самом конце, последний переход в вычислении s для логистической функции потерь.
Для простоты обозначим y_{i} * a_{N - 1}(x_{i}) за x, теперь проделаем последний переход:
(sigmoid(x) - 1) * y = (1 / (1 + exp(-x)) - 1) * y = ( (1 - 1 - exp(-x)) / (1 + exp(-x)) ) * y = 
= ( (-exp(-x)) / (1 + exp(-x)) ) * y = ( -1 / (exp(x) + 1) ) * y = -y / (exp(x) + 1) != y / (exp(x) + 1)

**Comment by alexeyum** [comment]
Поправил, спасибо
