### ISSUE TITLE
Оценивание математического ожидания в ДЗ - 3

### ISSUE THREAD

**Issue by ADKosm** [esokolov/ml-course-hse#18]
Вот здесь: https://github.com/esokolov/ml-course-hse/blame/master/2016-fall/homeworks-practice/homework-practice-03-ensembles.ipynb#L27

Кажется, что для оценивания мат.ожинания нужно не только складывать значения функции, а еще и делить на M, чтобы итоговая сумма все таки сошлась к искомому мат.ожиданию. Именно так и делается дальше, однако в формуле стоит просто сумма значений функции.

**Comment by nadiinchi** [comment]
Спасибо, поправила формулу!
