### ISSUE TITLE
Дз 3, деревья

### ISSUE THREAD

**Issue by ks-korovina** [esokolov/ml-course-hse#21]
Похоже, условием задачи на реализацию класса DecisionTree не учтено, что в выборке, в принципе, могут найтись два объекта с идентичным признаковым описанием и разными ответами. В таком случае требование выдавать класс объектов в листе некорректно. Связанный момент – стоит, наверное, уточнить, что должен возвращать стандартный вариант функции find_best_split, получив постоянный признак – кажется, например, что сгодится -inf оптимальный Джини, остальные возвращаемые значения None.

**Comment by nadiinchi** [comment]
Мы считаем, что выборка не противоречива, т. е. одинаковых объектов с разными ответами нет (впрочем, если эти ситуации будут корректно обработаны, хуже не будет :) . Функция find_best_split  в данном случае может вернуть любые 4 значения на усмотрение автора.  Добавила соответствующие оговорки в текст задания, спасибо!
На уже выполнивших эти пункты оговорки не влияют.
