### ISSUE TITLE
ДЗ#3, разделение в вершине

### ISSUE THREAD

**Issue by Koghtev** [esokolov/ml-course-hse#22]
Мы считаем критерий Джини для каждого разбиения - но он меняется при смене порога для правого и левого дерева, а не вершины. Из этого получается, что ответом тогда должен быть функционал качества, использующий посчитанные критерии для поддеревьев. Как понимаю, в Q(R) не используется H(R_m) как раз ввиду константности.

**Comment by nadiinchi** [comment]
Вадим, можете пояснить, в чем суть вопроса? :) Да, значение критерия информативности на самой вершине мы не считаем, потому что оно не влияет на выбор порога, зачем проводить лишние вычисления.

**Comment by Koghtev** [comment]
В задании требуется возвращать оптимальное значение критерия Джини и вектор таких значений для каждого порога. При этом для каждого порога мы имеем 2 таких критерия - для левого и правого поддерева

**Comment by nadiinchi** [comment]
Так ведь мы их усредняем с весами, пропорциональными числу объектов в поддеревьях (см. формулу в задании: "Под критерием Джини здесь подразумевается следующая функция:").

**Comment by Koghtev** [comment]
Да, видимо проблема в том, что на лекции подобная конструкция называлась функционалом ошибки.
