### ISSUE TITLE
ДЗ#3, Пропуски в данных

### ISSUE THREAD

**Issue by Sindbag** [esokolov/ml-course-hse#23]
При организации своего дерева не уточнено, что делать с пропусками в данных.
Надо ли проводить их обработку или можно их заполнить перед обучением дерева?

**Comment by nadiinchi** [comment]
Можно считать, что пропусков нет. Или как в sklearn инициировать исключение. Да, предполагается, что пропуски обрабатываются перед передачей данных в функцию обучения.
