### ISSUE TITLE
ДЗ 3, опечатка в задании 12

### ISSUE THREAD

**Issue by shihova-asya** [esokolov/ml-course-hse#26]
В задании 12:
1) 4й датасет называется **nursery**, а не nurcery
2) В описании 4го датасета не такие значения ответов, должно быть написано "читаем, что not_recom и **recommend** - класс 0, very_recom, priority, spec_prior - класс 1"

**Comment by shihova-asya** [comment]
В том же задании, в рекомендациях: "Чтобы cross_val_score вычисляла точность, нужно передать scorer=make_scorer(accuracy_score)", должно быть "**scoring**=make_scorer(accuracy_score)"

**Comment by nadiinchi** [comment]
Спасибо! Поправила.
