### ISSUE TITLE
Лекция №8, вывод Bias-Variance decomposition: забыт (x)

### ISSUE THREAD

**Issue by ischurov** [esokolov/ml-course-hse#29]
В формулах раздела 2 (Bias-Variance decomposition) начиная со страницы 4 встречается следующая опечатка: после $\mu(X)$ забыт $(x)$. Например, в ненумерованной формуле после формулы (2.1) присутствует выражение $(y-\mu(X))^2$, не имеющее смысла, поскольку $\mu(X)$ — это алгоритм, а $y$ — вектор. Здесь нужно написать $(y-\mu(X)(x))^2$. И далее нужно внести аналогичные исправления в последующие формулы.

**Comment by brainylyasha** [comment]
Внесли пояснение в текст
