### ISSUE TITLE
Лекция 13. Двойственное представление для линейной регрессии

### ISSUE THREAD

**Issue by VakhrameevaLiza** [esokolov/ml-course-hse#33]
Сначала записывается опт. задача для линейной регрессии через параметр Ф и получается обычная  задача для линейной регрессии с квадратичной функцией потерь, потом говорится, что w=(Ф.T)*a и ниже "можно показать, что оптимальное а=(Ф.T*Ф+lambda*I)^(-1)*y".

Тогда получается, что оптимальный вектор весов: w= (Ф.T)*a=(Ф.T)*(Ф.T * Ф+lambda*I)^(-1)*y. 
Но это же не правда, оптимальный вектор весов должен быть (Ф.T * Ф+lambda * I)^(-1) (Ф.T) * y ?

**Comment by esokolov** [comment]
Добрый вечер!

В той же лекции есть уравнение, которому должно удовлетворять решение задачи регуляризованной линейной регрессии: w = - (1 / lambda) Ф^T (Фw - y).
Вы можете проверить, что ему удовлетворяют обе записи для вектора весов. А поскольку решение у этой задачи единственное, то отсюда следует, что эти решения совпадают. Если не получится показать часть про выполнение уравнений — пишите.
