### ISSUE TITLE
Ошибка в методе Нистрома, лекция 14

### ISSUE THREAD

**Issue by posobin** [esokolov/ml-course-hse#51]
В методе Нистрома преобразование должно быть (K(x, x_1), …, K(x, x_n)) * G^{-1/2}, где G — матрица Грама для x_1, …, x_n, G^{-1/2} определяется по аналогии с G^{+}.

**Comment by passick** [comment]
Ну и в методе случайных признаков Фурье экспонента не равна косинусу, конечно, а просто интеграл от мнимой части ноль и поэтому рассматриваем только действительную часть.
