### ISSUE TITLE
Практическое ДЗ№7, метрики

### ISSUE THREAD

**Issue by MaydayMaydayMayday** [esokolov/ml-course-hse#56]
Кажется, вместо формул метрик в ДЗ указано что-то странное. Исправьте, пожалуйста.

**Comment by brainylyasha** [comment]
Подскажите, пожалуйста, что именно Вас смущает?

**Comment by MaydayMaydayMayday** [comment]
Извините за невнимательность, вчера показалось, что под суммами в правых частях то же самое, что в левых.

Ещё сбило с толку, что вводится много обозначений, которе в формулах не используются, особенно строчка "где g(r) — функция полезности фильма, а  d(i) — штраф за позицию" после формулы, в которой этих обозначений нет.
