### ISSUE TITLE
Неопределенность в 6 теоритическом дз fall 2017

### ISSUE THREAD

**Issue by Nazar1997** [esokolov/ml-course-hse#59]
В 1 и 2 пункте необходимо найти смещение, а в первом, используя константный алгортм, но все они зависят от вида ошибки, очевдно что там везде MSE тем не менее этого нет в задании

**Comment by nadiinchi** [comment]
Поскольку в курсе не было выведено другого смещения, кроме как для среднеквадратичной ошибки, не считаю нужным вносить это в задание. Добавление подобных пометок может запутать других студентов.
