### ISSUE TITLE
Задание 12, homework-practice-01

### ISSUE THREAD

**Issue by ilya160897** [esokolov/ml-course-hse#65]
12. [0.75 баллов] Предположим, что в данных была ошибка и Diet Coke (choice_description), который стоил $1.25, должен был стоить 1.35. Скорректируйте данные в таблицы и посчитайте, на какой процент больше денег было заработано с этого товара. Не забывайте, что количество товара не всегда равно 1.

Разве не очевидно, что именно с этого товара будет больше будет заработано на (1.35 / 1.25 - 1) * 100 = 8 процентов?

**Comment by Akiiino** [comment]
> emil kayumov
>> 1. изменилась цена только у того, что стоит x (а есть этот же товар с другой ценой).
>> 2. сравниваем выручки за этот товар целиком (при всех ценах)
