### ISSUE TITLE
Задания 9-10, homework-practice-01 

### ISSUE THREAD

**Issue by ivanashev-ilya** [esokolov/ml-course-hse#66]
Что является мерой популярности товара в задании 9, количество заказов, в которые он входит, или общее количество купленных единиц товара (сумма по quantity). Аналогичный вопрос по заданию 10, что учитывать как частоту покупки?

**Comment by Derrior** [comment]
Можно написать, как ты хочешь и считаешь правильным, и написать в клетке рядом, как именно считаешь популярность

**Comment by emilkayumov** [comment]
Да, главное указать, что вы посчитали популярностью. Я бы по quantity считал.
