### ISSUE TITLE
2019-fall/hw/01

### ISSUE THREAD

**Issue by TmLev** [esokolov/ml-course-hse#69]
> 5. [0.25 баллов] Какие 5 товаров были самыми дешёвыми и самыми дорогими? (по choice_description)

Что здесь подразумевается под (по choice_description)?

**Comment by AlexandraVolochova** [comment]
> > 1. [0.25 баллов] Какие 5 товаров были самыми дешёвыми и самыми дорогими? (по choice_description)
> 
> Что здесь подразумевается под (по choice_description)?

Опечатка, имелось в виду по item_name
Спасибо, что заметили :)

**Comment by TmLev** [comment]
> имелось в виду по item_name

А что делать с товарами, у которых одинаковые item_name, но разные choice_description?
Считать их разными или объединять в один?

**Comment by AlexandraVolochova** [comment]
Считайте разными
