### ISSUE TITLE
2019-fall/hw/01

### ISSUE THREAD

**Issue by MaratSaidov** [esokolov/ml-course-hse#72]
Как стоит понимать категорию из №9? Хочется использовать последнее слово из item_name: Bowl, Burrito, Drink и т.п.
Во №2 говорится обратное:
"Сколько уникальных категорий товара было куплено? (item_name)"
Означает ли это, что работаем с item_name?

**Comment by AlexandraVolochova** [comment]
Да, работайте с item_name
