### ISSUE TITLE
Доступность авторских решений

### ISSUE THREAD

**Issue by SerVB** [esokolov/ml-course-hse#75]
В своем решении первого домашнего задания мне было непонятно, как сделать пункты 1.12, 2.2, 2.3 и 2.4. Я написал об этом в файле работы, а также попросил рассказать правильное решение этих задачек. Ответа так и не получил.

Я спросил об авторских решениях у Дани Яшкова (семинариста), Даня попросил задать этот вопрос здесь.

Мне действительно хочется узнать правильное и красивое решение особенно части 2 Д/З, так как навыки рисования графиков потребуются не только в следующих заданиях, но и по жизни 😊

Соответственно, прошу рассказать, как парсить колонку `choice_description` и как подготавливать данные в задачах 2.2-2.4.

**Comment by AlexandraVolochova** [comment]
Мне бы не хотелось публиковать авторские решения, давайте вы мне в личку напишите и мы с вами обсудим

**Comment by SerVB** [comment]
Окей, написал Вам. Закрываю issue.
