### ISSUE TITLE
2019-fall/hw/03

### ISSUE THREAD

**Issue by Kirili4ik** [esokolov/ml-course-hse#82]
В комментариях к классу написано:
>         eta: learning rate
>         alpha: momentum coefficient
А в задании 5 просят:
> Исследуйте влияние параметров max_iter и alpha на процесс оптимизации. 

Нужно ли исследовать влияние коэффициента в методе momentum или произошла путаница и надо исследовать влияние learning rate?

**Comment by Kokhtev** [comment]
Для momentum нужно исследовать max_iter, alpha и eta, для остальных методов max_iter и eta
