### ISSUE TITLE
2019-fall/hw/04

### ISSUE THREAD

**Issue by asanikushin** [esokolov/ml-course-hse#83]
В 7 задании надо посмотреть только на поведение шума с фиксированным значением сглаживания `C = 10`?
Или сначала посмотреть на поведение при разных `C` без шума, а потом посмотреть как влияет шум с лучшим показателем сглаживания?

**Comment by emilkayumov** [comment]
Достаточно сначала без сглаживания подобрать адекватный уровень шума, а дальше использовать его. Можно попробовать при добавлении сглаживания уменьшить уровень шума.
