### ISSUE TITLE
2019-fall/hw5

### ISSUE THREAD

**Issue by sshlvn** [esokolov/ml-course-hse#84]
В 3ьем задании на реализацию функции find_best_split в условии написано про необходимость выбрать минимальный сплит при равенстве прироста Джини. А что такое минимальный сплит? 
Кажется, что в контест на ОК заходит и ближайший сплит к левому краю, и ближайший сплит к середине вектора.

**Comment by bazpasha** [comment]
Минимальный сплит - сплит с минимальным значением порога
